package com.payment.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA Entity mapping to the 'accounts' table.
 *
 * ANNOTATIONS EXPLAINED:
 *   @Entity  - tells JPA this class is a managed persistent object.
 *   @Table   - explicitly names the DB table (avoids name-casing surprises).
 *   @Getter / @Setter / @NoArgsConstructor - Lombok generates boilerplate.
 *
 * We DON'T use @Data (Lombok) on JPA entities because @Data generates
 * equals/hashCode based on all fields, which causes subtle bugs with
 * lazy-loaded collections and detached entities. We only use @Getter/@Setter.
 */
@Entity
@Table(name = "accounts")
@Getter
@Setter
@NoArgsConstructor
public class Account {

    /**
     * @Id marks the primary key.
     * @GeneratedValue(IDENTITY) would use a DB sequence — but we use UUIDs
     * generated by the DB (gen_random_uuid() in the migration).
     * We use GenerationType.UUID so Hibernate generates it in Java before insert,
     * which allows us to know the ID before the DB call (useful for logging).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @Column(name = "email", nullable = false, unique = true, length = 255)
    private String email;

    @Column(name = "full_name", nullable = false, length = 255)
    private String fullName;

    @Column(name = "is_active", nullable = false)
    private boolean isActive = true;

    /**
     * @CreationTimestamp - Hibernate sets this once on INSERT, never again.
     * @UpdateTimestamp   - Hibernate updates this on every UPDATE automatically.
     * Both work without any application code — purely managed by Hibernate.
     * 'updatable = false' on createdAt ensures it truly never changes.
     */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false, nullable = false)
    private OffsetDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    /** Convenience constructor for creating new accounts. */
    public Account(String email, String fullName) {
        this.email = email;
        this.fullName = fullName;
        this.isActive = true;
    }
}
