package com.payment.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * JPA Entity mapping to the 'payment_requests' table.
 *
 * This represents a single INTENT to pay — created once per checkout.
 * It is the top-level object that ties everything together:
 *   PaymentRequest → PaymentOrder(s) → LedgerEntries
 *
 * KEY: checkout_uuid carries idempotency. If the same checkout_uuid
 * arrives twice (network retry, button double-click), the DB UNIQUE
 * constraint on checkout_uuid will throw a DataIntegrityViolationException
 * which we catch and return a 409 Conflict.
 *
 * @Enumerated(EnumType.STRING): store the enum name as text ("PENDING")
 * not as an integer (0). Always prefer STRING — if you reorder the enum,
 * ordinal-based storage silently corrupts your data.
 */
@Entity
@Table(name = "payment_requests")
@Getter
@Setter
@NoArgsConstructor
public class PaymentRequest {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** The idempotency key — generated by the client on the checkout page. */
    @Column(name = "checkout_uuid", nullable = false, updatable = false)
    private UUID checkoutUuid;

    @Column(name = "user_id", nullable = false)
    private UUID userId;

    @Column(name = "from_account_id", nullable = false)
    private UUID fromAccountId;

    @Column(name = "to_account_id", nullable = false)
    private UUID toAccountId;

    @Column(name = "amount", nullable = false, precision = 19, scale = 4)
    private BigDecimal amount;

    @Column(name = "currency", nullable = false, length = 3)
    private String currency = "USD";

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_option", nullable = false, length = 50)
    private PaymentOption paymentOption;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private PaymentStatus status = PaymentStatus.PENDING;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false, nullable = false)
    private OffsetDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;
}
